# PLui CI configure

name: PLui CI

on:
  push:
    branches:
    - master
    - test
    - dev/*
    - hotfix/*
  pull_request:
    branches:
    - master
    - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the item from github
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get yarn cache path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: enter into itemDir
      run: |
        cd ./dev
        ls

    - uses: actions/cache@v1
      id: yarn-cache
      with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        cd ./dev
        pwd
        yarn

    - name: Build
      run: |
        cd ./dev
        pwd
        yarn build

    - name: Test
      run: |
        cd ./dev
        pwd
        yarn test
