# PUBLISH_MINOR CI configure

name: PUBLISH_NINOR CI

on:
    push:
        tags:
            - "minor-*.*.*"
            - "minor_*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone the item from github
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.TOKEN }}

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
                  registry-url: https://registry.npmjs.org/

            - name: Get yarn cache path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v1
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: |
                  cd ./dev
                  yarn

            - name: Lint
              run: |
                  cd ./dev
                  yarn lint

            - name: Get version
              id: get_version
              run: |
                  echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}

            - name: Build
              run: |
                  cd ./dev
                  yarn build
                  echo "Build work success! will publish to npmjs..."

            - name: Publish pkg
              run: |
                  cd ./dev
                  npm version minor
                  npm publish --access public
              shell: bash
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

            - uses: EndBug/add-and-commit@v6.2.0
              with:
                  author_name: Github Action as PlogCI
                  author_email: 1061393710@qq.com
                  message: "CI: new minor of package for plui ${{ steps.get_version.outputs.VERSION }}"
                  branch: master
                  remove: "./dev/yarn.lock"
                  token: ${{ secrets.TOKEN }}
